const photos = [
  {src: 'Prova1/Fotos/1.png', correctLabel: 'Tuberculose'},
  {src: 'Prova1/Fotos/2.png', correctLabel: 'Tuberculose'},
  {src: 'Prova1/Fotos/3.png', correctLabel: 'Tuberculose'},
  {src: 'Prova1/Fotos/4.png', correctLabel: 'Sífilis'},
  {src: 'Prova1/Fotos/5.png', correctLabel: 'Sífilis'},
  {src: 'Prova1/Fotos/6.png', correctLabel: 'Sífilis'},
  {src: 'Prova1/Fotos/7.png', correctLabel: 'Sífilis'},
  {src: 'Prova1/Fotos/8.png', correctLabel: 'Sífilis'},
  {src: 'Prova1/Fotos/9.png', correctLabel: 'Candidíase'},
  {src: 'Prova1/Fotos/10.png', correctLabel: 'Candidíase'},
  {src: 'Prova1/Fotos/11.png', correctLabel: 'Candidíase'},
  {src: 'Prova1/Fotos/12.png', correctLabel: 'Candidíase'},
  {src: 'Prova1/Fotos/13.png', correctLabel: 'Paracoccidioidomicose '},
  {src: 'Prova1/Fotos/14.png', correctLabel: 'Paracoccidioidomicose '},
  {src: 'Prova1/Fotos/15.png', correctLabel: 'Paracoccidioidomicose '},
  {src: 'Prova1/Fotos/16.png', correctLabel: 'Paracoccidioidomicose '},
  {src: 'Prova1/Fotos/17.png', correctLabel: 'Hiperplasia fibrosa'},
  {src: 'Prova1/Fotos/18.png', correctLabel: 'Granuloma piogênico'},
  {src: 'Prova1/Fotos/19.png', correctLabel: 'Granuloma piogênico'},
  {src: 'Prova1/Fotos/20.png', correctLabel: 'Granuloma piogênico'},
  {src: 'Prova1/Fotos/21.png', correctLabel: 'Fibroma ossificante periférico'},
  {src: 'Prova1/Fotos/22.png', correctLabel: 'Fibroma ossificante periférico'},
  {src: 'Prova1/Fotos/23.png', correctLabel: 'Fibroma ossificante periférico'},
  {src: 'Prova1/Fotos/24.png', correctLabel: 'Lesão periférica de células gigantes'},
  {src: 'Prova1/Fotos/25.png', correctLabel: 'Lesão periférica de células gigantes'},
  {src: 'Prova1/Fotos/26.png', correctLabel: 'Lesão periférica de células gigantes'},
  {src: 'Prova1/Fotos/27.png', correctLabel: 'Lipoma'},
  {src: 'Prova1/Fotos/28.png', correctLabel: 'Lifangioma'},
  {src: 'Prova1/Fotos/29.png', correctLabel: 'Papiloma escamoso'},
  {src: 'Prova1/Fotos/30.png', correctLabel: 'Papiloma escamoso'},
  {src: 'Prova1/Fotos/31.png', correctLabel: 'Papiloma escamoso'},
  {src: 'Prova1/Fotos/32.png', correctLabel: 'Papiloma escamoso'},
  {src: 'Prova1/Fotos/33.png', correctLabel: 'Schwannoma'},
  {src: 'Prova1/Fotos/34.png', correctLabel: 'Schwannoma'},
  {src: 'Prova1/Fotos/35.png', correctLabel: 'Schwannoma'}
];